### ISSUE TITLE
Doesn't work with Vaadin 25.0.4

### ISSUE THREAD

**Issue by SapogaN** [vaadin-component-factory/lumo-paper-slider#2]
Hello!

com.vaadin.flow.component.FocusNotifier.FocusEvent now has 3 arguments in it's constructor, not 2.
com.vaadin.flow.component.BlurNotifier.BlurEvent now has 3 arguments in it's constructor, not 2.

## Expected Behavior
Works normally

## Actual Behavior
```
java.lang.NoSuchMethodError: com.vaadin.flow.component.BlurNotifier$BlurEvent: method 'void <init>(com.vaadin.flow.component.Component, boolean)' not found
        at org.vaadin.addons.componentfactory.PaperSlider.lambda$new$a8baf231$2(PaperSlider.java:44)
        at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:242)
        at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:491)
        at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:301)
```

## Specifications

  - Version: 1.1.0
  - Platform: Vaadin 25.0.4
